# Generated by Django 4.2.7 on 2023-12-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('lugar_id', models.AutoField(primary_key=True, serialize=False)),
                ('lugar_nombre', models.CharField(max_length=50)),
                ('lugar_tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lugar',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={'managed': False},
        ),
    ]
