# Generated by Django 4.2.7 on 2024-01-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_lugar_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('beneficio_id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficio_nombre', models.CharField(max_length=50)),
                ('beneficio_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'beneficio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeneficioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'beneficio_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('horario_id', models.AutoField(primary_key=True, serialize=False)),
                ('horario_entrada', models.TimeField()),
                ('horario_salida', models.TimeField()),
                ('horario_dia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'horario_empleado',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='tienda',
            table='tienda',
        ),
    ]
