# Generated by Django 4.2.7 on 2023-12-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefono',
            options={'managed': False},
        ),
    ]
