# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_razon_social', models.CharField(max_length=50)),
                ('proveedor_den_comercial', models.CharField(max_length=100)),
                ('proveedor_rif', models.CharField(max_length=50)),
                ('proveedor_dir_fisica', models.CharField(max_length=100)),
                ('proveedor_dir_fiscal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
    ]
