# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botella',
            fields=[
                ('botella_id', models.AutoField(primary_key=True, serialize=False)),
                ('botella_nombre', models.CharField(max_length=50)),
                ('botella_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('botella_capacidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('botella_ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('botella_alto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'botella',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_nombre', models.CharField(max_length=50)),
                ('color_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventario_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventario_descripcion', models.CharField(max_length=150)),
                ('inventario_cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('materia_prima_id', models.AutoField(primary_key=True, serialize=False)),
                ('materia_prima_nombre', models.CharField(max_length=50)),
                ('materia_prima_tipo', models.CharField(max_length=50)),
                ('materia_prima_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'materia_prima',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ron',
            fields=[
                ('ron_id', models.AutoField(primary_key=True, serialize=False)),
                ('ron_nombre', models.CharField(max_length=50)),
                ('ron_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ron',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tapa',
            fields=[
                ('tapa_id', models.AutoField(primary_key=True, serialize=False)),
                ('tapa_nombre', models.CharField(max_length=50)),
                ('tapa_descripcion', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tapa',
                'managed': False,
            },
        ),
    ]
