# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_venta_remove_premio_fk_evento_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('venta_cantidad', models.IntegerField()),
                ('venta_precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_venta', models.OneToOneField(db_column='fk_venta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='eventos.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('entrada_id', models.AutoField(primary_key=True, serialize=False)),
                ('entrada_fecha', models.DateField()),
                ('entrada_descripcion', models.CharField(max_length=150)),
                ('entrada_precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'entrada',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
