# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_telefono_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('correo_id', models.AutoField(primary_key=True, serialize=False)),
                ('correo_direccion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonaContacto',
            fields=[
                ('contacto_id', models.AutoField(primary_key=True, serialize=False)),
                ('contacto_nombre', models.CharField(max_length=50)),
                ('contacto_apellido', models.CharField(max_length=50)),
                ('contacto_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona_contacto',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='telefono',
            table='telefono',
        ),
    ]
