# Generated by Django 4.2.7 on 2023-12-19 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('afiliado_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('afiliado_fecha_afiliacion', models.DateField(unique=True)),
                ('afiliado_numero_carnet', models.CharField(max_length=10, unique=True)),
                ('afiliado_codigo_qr', models.CharField(max_length=10, unique=True)),
                ('FK_Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.tienda')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'db_table': 'Afiliado',
            },
        ),
        migrations.CreateModel(
            name='Cliente_natural',
            fields=[
                ('cliente_rif', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cliente_cantidad_puntos', models.IntegerField()),
                ('cliente_cedula', models.CharField(max_length=10, unique=True)),
                ('cliente_p_nombre', models.CharField(max_length=50)),
                ('cliente_s_nombre', models.CharField(max_length=50)),
                ('cliente_p_apellido', models.CharField(max_length=50)),
                ('cliente_s_apellido', models.CharField(max_length=50)),
                ('cliente_direccion', models.CharField(max_length=100)),
                ('FK_Afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.afiliado')),
            ],
            options={
                'verbose_name': 'Cliente Natural',
                'verbose_name_plural': 'Clientes Naturales',
                'db_table': 'Cliente_natural',
            },
        ),
        migrations.CreateModel(
            name='Cliente_juridico',
            fields=[
                ('cliente_rif', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('cliente_cantidad_puntos', models.IntegerField()),
                ('cliente_denominacion_comercial', models.CharField(max_length=50)),
                ('cliente_razon_social', models.CharField(max_length=50)),
                ('cliente_pagina_web', models.CharField(max_length=50)),
                ('cliente_capital_disponible', models.IntegerField()),
                ('cliente_direccion_fisica', models.CharField(max_length=100)),
                ('cliente_direccion_fiscal', models.CharField(max_length=100)),
                ('FK_Afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.afiliado')),
            ],
            options={
                'verbose_name': 'Cliente Juridico',
                'verbose_name_plural': 'Clientes Juridicos',
                'db_table': 'Cliente_juridico',
            },
        ),
    ]
