# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_afiliado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='afiliado',
            table='afiliado',
        ),
        migrations.AlterModelTable(
            name='cliente_juridico',
            table='cliente_juridico',
        ),
        migrations.AlterModelTable(
            name='cliente_natural',
            table='cliente_natural',
        ),
    ]
