# Generated by Django 4.2.7 on 2024-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('cheque_numero', models.IntegerField()),
                ('cheque_banco', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cheque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conversion_divisa',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cd_fecha_inicio', models.DateField()),
                ('cd_fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'conversion_divisa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('efectivo_denominacion', models.IntegerField()),
            ],
            options={
                'db_table': 'efectivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('punto_id', models.AutoField(primary_key=True, serialize=False)),
                ('punto_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('punto_fecha_inicio', models.DateField()),
                ('punto_fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'punto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntoMetodo',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('punto_metodo_cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'punto_metodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('metodo_pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarjeta_numero', models.CharField(max_length=50)),
                ('tarjeta_banco', models.CharField(max_length=50)),
                ('tarjeta_cvv', models.IntegerField()),
                ('tarjeta_fecha_vencimiento', models.DateField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
